[package]
name = "journald-space"
version = "0.3.0"
authors = ["lilydjwg <lilydjwg@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.systemd]
version = "*"

[profile.release]
lto = true
